version: "3.8"
services:
  api:
    build: ./api
    container_name: p1-api
    depends_on: 
      - db
    networks:
      - p1-net
  db:
    image: postgres:15.2-alpine
    container_name: p1-db
    restart: always
    volumes:
      - p1-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: geek
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: temp
    networks:
      - p1-net
  proxy-server:
    image: nginx:1.25.1
    container_name: p1-nginx
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - p1-net

volumes:
  p1-data:
    # external: true

networks:
  p1-net: