name: test-pipeline
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: echo "lint $(date)"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: echo "test $(date)"

  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile
        run: echo "compile $(date)"

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: release
        run: echo "release $(date)"